function autocomplete(inp, arr) {
  /*the autocomplete function takes two arguments,
  the text field element and an array of possible autocompleted values:*/
  var currentFocus;
  /*execute a function when someone writes in the text field:*/
  inp.addEventListener("input", function(e) {
      var a, b, i, val = this.value;
      /*close any already open lists of autocompleted values*/
      closeAllLists();
      if (!val) { return false;}
      currentFocus = -1;
      /*create a DIV element that will contain the items (values):*/
      a = document.createElement("DIV");
      a.setAttribute("id", this.id + "autocomplete-list");
      a.setAttribute("class", "autocomplete-items");
      /*append the DIV element as a child of the autocomplete container:*/
      this.parentNode.appendChild(a);
      /*for each item in the array...*/
      for (i = 0; i < arr.length; i++) {
        /*check if the item starts with the same letters as the text field value:*/
        if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
          /*create a DIV element for each matching element:*/
          b = document.createElement("DIV");
          /*make the matching letters bold:*/
          b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
          b.innerHTML += arr[i].substr(val.length);
          /*insert a input field that will hold the current array item's value:*/
          b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
          /*execute a function when someone clicks on the item value (DIV element):*/
              b.addEventListener("mousedown", function(e) {
              /*insert the value for the autocomplete text field:*/
              inp.value = this.getElementsByTagName("input")[0].value;
              /*close the list of autocompleted values,
              (or any other open lists of autocompleted values:*/
              closeAllLists();
              updateStats();
          });
          a.appendChild(b);
        }
      }
  });
  /*execute a function presses a key on the keyboard:*/
  inp.addEventListener("keydown", function(e) {
      var x = document.getElementById(this.id + "autocomplete-list");
      if (x) x = x.getElementsByTagName("div");
      if (e.keyCode == 40) {
        /*If the arrow DOWN key is pressed,
        increase the currentFocus variable:*/
        currentFocus++;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 38) { //up
        /*If the arrow UP key is pressed,
        decrease the currentFocus variable:*/
        currentFocus--;
        /*and and make the current item more visible:*/
        addActive(x);
      } else if (e.keyCode == 13) {
        /*If the ENTER key is pressed, prevent the form from being submitted,*/
        e.preventDefault();
        if (currentFocus > -1) {
          /*and simulate a click on the "active" item:*/
          if (x) {triggerMouseEvent(x[currentFocus], "mousedown"); }
          triggerMouseEvent(x[currentFocus], "mouseup");
        }
      } else if (e.keyCode == 9) {
        /*If the TAB key is pressed, prevent the form from being submitted,*/
        if (currentFocus > -1) {
          /*and simulate a click on the "active" item:*/
          if (x) {triggerMouseEvent(x[currentFocus], "mousedown"); }
          triggerMouseEvent(x[currentFocus], "mouseup");
        }
      }
  });
  function addActive(x) {
    /*a function to classify an item as "active":*/
    if (!x) return false;
    /*start by removing the "active" class on all items:*/
    removeActive(x);
    if (currentFocus >= x.length) currentFocus = 0;
    if (currentFocus < 0) currentFocus = (x.length - 1);
    /*add class "autocomplete-active":*/
    x[currentFocus].classList.add("autocomplete-active");
  }
  function removeActive(x) {
    /*a function to remove the "active" class from all autocomplete items:*/
    for (var i = 0; i < x.length; i++) {
      x[i].classList.remove("autocomplete-active");
    }
  }
/*  function closeAllLists(elmnt) {
    /*close all autocomplete lists in the document,
    except the one passed as an argument:
    var x = document.getElementsByClassName("autocomplete-items");
    for (var i = 0; i < x.length; i++) {
      if (elmnt != x[i] && elmnt != inp) {
      x[i].parentNode.removeChild(x[i]);
    }
  }*/
}

function triggerMouseEvent (node, eventType) {
    var clickEvent = document.createEvent ('MouseEvents');
    clickEvent.initEvent (eventType, true, true);
    node.dispatchEvent (clickEvent);
}

function closeAllLists(elmnt) {
  /*close all autocomplete lists in the document,
  except the one passed as an argument:*/
  var x = document.getElementsByClassName("autocomplete-items");
  for (var i = 0; i < x.length; i++) {
    if (elmnt != x[i] && elmnt != document.getElementById("mobName")) {
    x[i].parentNode.removeChild(x[i]);
    }
  }
}

/*execute a function when someone clicks in the document:*/
document.addEventListener("click", function (e) {
    closeAllLists(e.target);
});


var mobNames = ['Blue Larva',
'Green Larva',
'Gobball',
'Crackler',
'Coney',
'Boar',
'Prespic',
'The Ultra-Powerful',
'Tofu',
'Bwork Magus',
'Enraged Kitten',
'Orange Larva',
'Treechnid',
'Wild Sunflower',
'Arachnee',
'Bwork Magus',
'Chafer',
'Blue Jelly',
'Mint Jelly',
'Strawberry Jelly',
'Royal Blue Jelly',
'Mush Mush',
'Moskito',
'Karne Rider',
'Crab',
'Wabbit',
'Black Wabbit',
'Black Tiwabbit',
'Tiwabbit Wosungwee',
'Bwork Archer',
'Immature Golden Dreggon',
'White Dreggon',
'Demonic Rose',
'Evil Dandelion',
'Wind Kwak',
'Immature Black Dreggon',
'Fire Kwak',
'Ice Kwak',
'Royal Mint Jelly',
'Royal Strawberry Jelly',
'Golden Dreggon',
'Sapphire Dreggon',
'Black Dreggon',
'Immature White Dreggon',
'Alert Black Dreggon',
'Alert White Dreggon',
'Alert Golden Dreggon',
'Alert Sapphire Dreggon',
'Tiwabbit',
'Wo Wabbit',
'Tofu',
'Gwandpa Wabbit',
'Gobball',
'Boowolf',
'Prespic',
'Boar',
'Crackler',
'Dark Vlad',
'Rib',
'Invisible Chafer',
'Evil Tofu',
'Mushd',
'Dragon Pig',
'The Madoll',
'The Sacrificial Doll',
'The Inflatable',
'Dark Miner',
'Dark Smith',
'Thrown Tofu',
'Minotoror',
'Piglet',
'Vampire Master',
'Grey Mouse',
'Vampire',
'White Gobbly',
'Royal Gobball',
'Gobball War Chief',
'Black Gobbly',
'Neye',
'The Swindling',
'Dark Baker',
'Kwoan',
'Rogue Clan Bandit',
'Arachnid',
'Explosive Shell',
'Snoowolf',
'Feca Dopple',
'Osamodas Dopple',
'Enutrof Dopple',
'Sram Dopple',
'Xelor Dopple',
'Ecaflip Dopple',
'Eniripsa Dopple',
'Iop Dopple',
'Cra Dopple',
'Sadida Dopple',
'Immature Sapphire Dreggon',
'Wild Almond Dragoturkey',
'Ancestral Treechnid',
'Goblin',
'Skeleton Wabbit',
'Wa Wabbit',
'Wobot',
'GM Wabbit',
'Red Scaraleaf',
'Blue Scaraleaf',
'Wild Ginger Dragoturkey',
'Pumpkwin',
'Tikokoko',
'Kokoko',
'Kanniball Archer',
'Kanniball Thierry',
'Kanniball Jav',
'Kanniball Sarbak',
'Glukoko',
'Greedovore',
'Ambusher',
'Kokonut',
'Red Turtle',
'Blue Turtle',
'Green Turtle',
'Yellow Turtle',
'Darkli Moon',
'Moon',
'Boomba',
'Hazwonarm',
'LeChouque',
'Cannon Dorf',
'Moowolf',
'Trool',
'Earth Kwak',
'Purple Piwi',
'Living Shovel',
'Red Wyrmling',
'Green Scaraleaf',
'White Scaraleaf',
'Fire Spark',
'Water Spark',
'Earth Spark',
'Air Spark',
'Arachnee',
'Impette',
'Oni',
'Needle',
'Smiths\', Chest',
'Dark Treechnid',
'Venerable Treechnid',
'Aggressive Arachnee',
'Trunknid',
'Soft Oak',
'Summoning Branch',
'Major Arachnee',
'Healing Branch',
'Crocodyl',
'Chaferfu',
'Crocodyl Chief',
'Xelor\',s Dial',
'Fire Bwak',
'Earth Bwak',
'Air Bwak',
'Water Bwak',
'Fire Kwakere',
'Earth Kwakere',
'Ice Kwakere',
'Wind Kwakere',
'Coco Blop',
'Indigo Blop',
'Morello Cherry Blop',
'Pippin Blop',
'Indigo Biblop',
'Coco Biblop',
'Morello Cherry Biblop',
'Pippin Biblop',
'Crobak',
'Living Chest',
'Kaniger',
'Plissken',
'Lord Crow',
'Chafer Lancer',
'Chafer Archer',
'Elite Chafer',
'Plain Crackler',
'Green Mouse',
'Militiaman',
'Plain Boar',
'Scurvion',
'Whitish Fang',
'Kolerat',
'Ouginak',
'Lousy Pig Knight',
'Lousy Pig Shepherd',
'Mak Gahan',
'Fungi Master',
'Warrior',
'Burning Ghost',
'Brave Ghost',
'Ghost Hicidal',
'Royal Tofu',
'Aboub',
'Amlub',
'Codem',
'Gink',
'Kirevam',
'Let Emoliug',
'Nebgib',
'Nipul',
'Osurc',
'Susej',
'Knight',
'Chafer Foot Soldier',
'Furious Whitish Fang',
'Healing Shell',
'Sapphire Larva',
'Ruby Larva',
'Emerald Larva',
'Dark Vlad Dopple',
'Giant Kralove',
'First Tentacle',
'Lemon Jelly',
'Royal Lemon Jelly',
'Dancing Sword',
'Flying Sword',
'Imp',
'Grossewer Rat',
'Aermyne \',Braco\', Scalptaras',
'Grossewer Shaman',
'Hyoactive Rat',
'Sewer Keeper',
'Bearman',
'Bear',
'Sacrier Dopple',
'Golden Larva',
'Shin Larva',
'Nomarow Transplent',
'Stellia Blutzell',
'Ogivol Scalarcin',
'Akornaddikt the Squirrel',
'Brumen Tinctorias',
'Sick Grossewer Rat',
'One-Armed Bandit',
'Dark Rose',
'Sick Tofu',
'Sick Arachnee',
'Sick Grossewer Milirat',
'Bworker',
'Mama Bwork',
'Moumouse',
'Qil Bil',
'Crackrock',
'Elemental Fire Bwork',
'Elemental Water Bwork',
'Elemental Air Bwork',
'Elemental Earth Bwork',
'Cybwork',
'Red Piwi',
'Green Piwi',
'Blue Piwi',
'Pink Piwi',
'Yellow Piwi',
'Ouassingal',
'Ouassingue',
'Gargoyl',
'Pandawasta',
'Rok Gnorok',
'Musha the Oni',
'Marzwel the Goblin',
'Zatoishwan',
'Yadrutas',
'Pandikaze Ghost',
'Maho Firefoux Ghost',
'Soryo Firefoux Ghost',
'Leopardo Ghost',
'Yokai Firefoux Ghost',
'Tanukouï San Ghost',
'Pandulum Ghost',
'Tanuki Chan Ghost',
'Tanuki Chan Ghost',
'Tanuki Chan Ghost',
'Tanuki Chan Ghost',
'Pandora Ghost',
'Tanuki Chan Ghost',
'Blodz Uker',
'Dorgan Ation',
'Farle\',s Pig',
'Pandora Ghost Bokse',
'Dark Chest',
'Treechnee',
'Dark Treechnee',
'Green Spimush',
'Red Spimush',
'Blue Spimush',
'Brown Spimush',
'Wild Golden Dragoturkey',
'Minokid',
'Legendary Crackler',
'Koolich',
'Cave Gobball',
'Gobkool',
'Emeralda',
'Emerald Doll',
'Sapphira',
'Starving Doll',
'Ruby',
'Motivating Totem',
'Explosive Totem',
'Healing Totem',
'Diamondine',
'Lethal Doll',
'Bloody Koalak',
'Purple Warko',
'Brown Warko',
'Dok Alako',
'Immature Koalak',
'Koalak Warrior',
'Indigo Koalak',
'Coco Koalak',
'Morello Cherry Koalak',
'Pippin Koalak',
'Mama Koalak',
'Wild Koalak',
'Koalak Master',
'Koalak Rider',
'Koalak Mummy',
'Koalak Gravedigger',
'Workette',
'Drakoalak',
'Skeunk',
'Reapalak',
'Piralak',
'Koalak Forester',
'Fisheralak',
'Fiery Adventurer Ghost',
'Arepo Adventurer Ghost',
'Brave Adventurer Ghost',
'Tamed Trool',
'Bworkette',
'Al Howin Gobball',
'Al Howin Tofu',
'Black Scaraleaf',
'Black Tofu',
'Golden Scarabugly',
'Immature Scaraleaf',
'Famished Sunflower',
'Batofu',
'Bomberfu',
'Tofoone',
'Mutant Tofu',
'Tofukaz',
'Tofuzmo',
'Tofurby',
'Tamed Crobak',
'Drinker',
'Crowfox',
'Foxo the Crowfox',
'Horace the Tamed Crobak',
'Kapotie the Drinker',
'Eroded Kirball',
'Minotot',
'Jellidice',
'Quetsnakiatl',
'Scaratos',
'Mumminotor',
'Deminoball',
'Minoskito',
'Manderisha',
'Khamelerost',
'Abominable Snow Yiti',
'Wintry Kaniger',
'Frozen Tofu',
'Snowman',
'Icikle',
'Hibernal Tofu',
'Black Dragoss',
'Pricky',
'Dreggon Warrior',
'Crocabulia',
'Dragostess',
'Alert Black Dragoss',
'Flying Dreggon',
'Sakai Firefoux',
'Snowball',
'Snowy Tofu',
'Ice Crackler',
'Larvicy',
'Larvicily',
'Father Kwismas',
'Half Father Kwismas',
'Bwork',
'Aqualikros the Merciless',
'Alert White Dragoss',
'Alert Golden Dragoss',
'Stuk\',kiddy',
'Chop\',kiddy',
'Pop\',Kiddy',
'Sapphire Dragoss',
'White Dragoss',
'Golden Dragoss',
'Prez\', Ent',
'Prez\', Plozion',
'Prez\', Pertize',
'Baby Prez',
'Mini Inuit',
'Terrakubiack the Warrior',
'Ignilicrobur the Warrior',
'Aeroktor the Warrior',
'Aquabralak the Warrior',
'Kitsou Nakwatus',
'Black Tiwabbitus',
'Kwakus',
'Ignirkocropos the Famished',
'Terraburkahl the Perfidious',
'Aerogoburius the Malicious',
'Alert Sapphire Dragoss',
'Prez',
'Minimini Inuit',
'Arachnotron',
'Sick Treechnid',
'Orange Snapper',
'Blue Snapper',
'White Snapper',
'Green Snapper',
'Kloon Snapper',
'Raul Mops',
'Starfish Trooper',
'Sponge Mob',
'Apero Ghost',
'Rat Suenami',
'Rat Tchet',
'Rat Bag',
'Rat Basher',
'Black Rat',
'White Rat',
'Rat Pakk',
'Rat Rah',
'Sphincter Cell',
'Raphaela',
'Donatella',
'Michelangela',
'Leonardawa',
'Mumussel',
'Feca Dopple',
'Enutrof Dopple',
'Sram Dopple',
'Xelor Dopple',
'Ecaflip Dopple',
'Eniripsa Dopple',
'Iop Dopple',
'Cra Dopple',
'Sadida Dopple',
'Pandawa Dopple',
'Young White Gobbly',
'Immature Blue Larva',
'Immature Orange Larva',
'Immature Green Larva',
'Vulnerable Mush Mush',
'Small Gobball War Chief',
'Short-Tempered Treechnid',
'Short-Tempered Arachnotron',
'Short-Tempered Dark Treechnid',
'Short-Tempered Dark Treechnee',
'Incarnam Scarecrow',
'Livid Boowolf',
'Training Scarecrow',
'Obese Tofu Mummy',
'Force-fed Obese Tofu',
'Obese Tofu Daddy',
'Wa Wabbit',
'Plain Pikoko',
'Air Pikoko',
'Coralator',
'Polished Crackler',
'Polished Crackrock',
'Great Coralator',
'Floramor',
'Dark Pikoko',
'Cheeken',
'Snailmet',
'Kimbo',
'Moopet',
'Light Treeckler',
'Sparo',
'Barbrossa',
'Ze Flib',
'Gourlo the Terrible',
'Zoth Master',
'Zoth Girl',
'Zoth Warrior',
'Zoth Disciple',
'Zoth Sergeant',
'Mopy King',
'Mopeat',
'Miremop',
'Kurasso Craboral',
'Mahlibuh Craboral',
'Passaoh Craboral',
'Mojeeto Craboral',
'Kurasso Palmflower',
'Mahlibuh Palmflower',
'Passaoh Palmflower',
'Mojeeto Palmflower',
'Mufafah',
'Kido',
'Kilibriss',
'Silf the Greater Bherb',
'Dismayed Tynril',
'Rotaflor',
'Gwass',
'Barkritter',
'Warguerite',
'Dark Treeckler',
'Flib\',s Cursed Chest',
'Pirate Barrel',
'Boomba Shika',
'Lesser Bherb',
'Disconcerted Tynril',
'Perfidious Tynril',
'Stunned Tynril',
'Kimbo\',s Disciple',
'Fourth Tentacle',
'Third Tentacle',
'Second Tentacle',
'Boggedown Ouassingue',
'Chaferfu Lancer',
'Bontarian Warrior',
'Brakmarian Warrior',
'Trumperelle',
'Mushnid',
'Mushmunch',
'Mush Mish',
'Mush Tup',
'Mush Rhume',
'Ougaa',
'Exploding Spimush',
'Itzting',
'Pokipik',
'Greedoblop',
'Blopshroom',
'Trunkiblop',
'Royal Coco Blop',
'Royal Morello Cherry Blop',
'Royal Indigo Blop',
'Royal Pippin Blop',
'Royal Rainbow Blop',
'Dark Vlad Puppet',
'Royal Gobball Puppet',
'Dragon Pig Puppet',
'Minotoror Puppet',
'Boowolf Puppet',
'Father Whupper',
'Drunken Boomba',
'Beginner Cannon Dorf',
'Lonely Hazwonarm',
'Chocrosis Gobball',
'Piralhaka the Intimidator',
'Fisheralf the Stewart',
'Snappy the Fishfrier',
'Rattle the Hummer',
'Ratilla the Hun',
'Rib the Torn',
'Zorrose the Messican',
'Boarealis the Bright',
'Scaratheef the Pincher',
'Scarahazad the Storyteller',
'Scarabreef the Short',
'Scaramel the Melty',
'Scorbison the Lonely',
'Buzzby the Social',
'Quetnin the Fictional',
'Suzessman the Enthusiastic',
'Bignstrong the Quartermaster',
'Tiwaldo the Hidden',
'Tiwascal the Wapper',
'Turtan\',ernie the Streetwise',
'Turtrenalds the Tragic',
'Turticorn the Horned',
'Turture the Hooded',
'Trunkbeard the Gentle',
'Trooligan the Bulldogg',
'Glukoko the Slow',
'Vamp the Impalest',
'McWhabbit the Diehard',
'Wabbitor the Apt',
'Warko the Inky',
'Worka the Willful',
'Wowalker the Egyptian',
'Treekniddioo the Needy',
'Arakula the Carpature',
'Arachma the Greek',
'Arachnangel the Hopeful',
'Bandirty the Messy',
'Bandinamit the Explosive',
'Gobbach the Contrapuntaler',
'Gobballyhoo the Noisy',
'Gobballad the Romantic',
'Bakeraider the Tomb',
'Chaferanho the Essential',
'Chaferotix the Sixtininth',
'Chafaldrag the Charming',
'Chafermented the Drinker',
'Matmushmush the Flasher',
'Gobbalky the Stubborn',
'Pigoblet the Useful',
'Crackrockisree the Tiger',
'Krabaoly the Patient',
'Smitherz the Licker',
'Larvalencia the Orange',
'Larvadelaide the Ozie',
'Milivanilli the Mime',
'Miliopold the Bloomer',
'Minoskittle the Coloured',
'Moskoitus the Interruptor',
'Booty the Beast',
'Snappu the Shopkeep',
'Snappster the Sued',
'Snapp the Dragon',
'Piwiki the Witty',
'Piwicker the Manly',
'Piwi the Ermine',
'Piwilde the Bossie',
'Piwiliam the Brave',
'Snapple the Wise',
'Piwinston the Churlish',
'Dandel the Boy',
'Prestreet the Fighter',
'Ratatouille the Stirrer',
'Raul Modrid the Chulo',
'Roseanne the Yanker',
'Boarnigen the Damasker',
'Famouse the Little-Known',
'Tofudd the Hunter',
'Tofull the Optimist',
'Tofulsom the Jailer',
'Hunflower the Sinful',
'Fung Ku the Master',
'Barkricrac the Unsteady',
'Mopfeet the Circular',
'Mopidyk the Mire',
'Drakween the Cross Dresser',
'Dreggershween the Tinpanalley',
'Dreggonzola the Cheesy',
'Leorio the Haunted',
'Jelleno the Chinny',
'Dreggatón the Latino',
'Romush the Montecchi',
'Satonuki the Plastikpaddy',
'Jellyposukshion the Slim',
'Dragamemnon the Deadtroyer',
'Snowhitisha the Pure',
'Dragotitis the Painful',
'Treekstalbal the Psychic',
'Follikoko the Tufted',
'Cheech the Pussycat',
'Abounteous the Generous',
'Treeknidylus',
'Treekalack the Sad',
'Treekonk the Stunned',
'Treektamak the Loud',
'Amlullabeye the Dreamer',
'Arachnekros the Aggressive',
'Billbiblop the Great',
'Pigstol the Sexy',
'Biblopopo the Organiser',
'Biblokajin the Bald',
'Bibloponey the Entertainer',
'Tiwana the Tokin\',',
'Wabbin the Wich',
'Blopulent the Pretentious',
'Blorchid the Gorgeous',
'Blopium the Delirious',
'Blopal the Precious',
'Boombora the Dangerous',
'Bworak the Bohemian',
'Blorko the Colourful',
'Bworkoder the Mazter',
'Ganon the Dwarf',
'Pygknightlion the Lousy',
'Chafred the Fish',
'Chaferuption the Volcanic',
'Shamassel the Off',
'Spimushty the Smelly',
'Speedmush the Racer',
'Spimushuaia the Traveller',
'Spimushtache the Hairy',
'Crokdylann the Rebel',
'Koelloggs the Creator',
'Karnyona the Rider',
'Jackellington the Lantewn',
'Pighatchoo the Electrical',
'Codemonic the Mean',
'Jiminicrackler the Conscious',
'Crowmanion the Primitive',
'Cracklerod the Old',
'Croccyx the Bummer',
'Lupisnockio the Woodwolf',
'Dokterwho the Tardisporter',
'Dreggoog the Downunder',
'Dreggooniz the Adventurous',
'Dreggrieg the Pianist',
'Dreggooliz the Macho',
'Dreggommomm the Chewer',
'Dreggump the Shrimp',
'Dragoolash the Stewed',
'Dragory the Violent',
'Dragaustin the Power',
'Dragorse the Wild',
'Dragostino the Tiny',
'Draigovsky the SocalledSwan',
'Dragospel the Black',
'Draghouse the Cynical',
'Dragoskovit the Barefoot',
'Dragossiper the Nag',
'Dragangora the Softy',
'Drakoamax the Mad',
'Dregguantico the Trainer',
'Drakokidoki the Volunteer',
'Aperobics the Dynamic',
'Polterghaisk the Stray Soul',
'Ghostabrava the Tourist',
'Pandipoopik the Wondrous',
'Pandoracle the Opposing Force',
'Pandumonium the Joker',
'Tanukhiraru the Gifted',
'TanuKiki the Deliveryghost',
'Tanukhuina the Drawer',
'Tanno the Dominator',
'Tanaked the Stalker',
'Tanuktonik the Doofdoof',
'Koalarchitect the Balancing Force',
'Yoksai the Spirited',
'Ambushapens the Unlucky',
'Gargoyla the Paranoiac',
'Jellvis the King',
'Ginsync the Hyperactive',
'Goblimp the Bis Kit',
'Greetdoff the Gentleman',
'Chukoalak the Norris',
'Gwabbit the Wunner',
'Kannimantha the Maneater',
'Kaniedoss the Giggling',
'Kannemik the Skinny',
'Kannarrie the Reckless',
'Kanniranda the Maniac',
'Kirevampiro the Wrestler',
'Crackoalak the Blonde',
'Jackoalak the Ripper',
'Koalsen the Similar',
'Popoalak the Mousibrown',
'Koaly the Fiddler',
'Koaldmen the Grumpy',
'Snapoalak the Redhead',
'Koaldman the Garish',
'Koleraspootin the Anesthesialogist',
'Khameleltux the Tolerant',
'Kwoanium the Smart',
'Ouassup the Irritating',
'Lert Macraken the Used Emo',
'Mamankalak the Bibliomaniac',
'Salamaa the Henpeck',
'Koalakropolis the King of the Hill',
'Lord Lacedhat the Vampiric',
'Milikkybum the Informer',
'Jackoalak the Moonwalker',
'Hazwonball the Hickler',
'Nebuchadnezzar the Conqueror',
'Niptuk the Plasticynic',
'Kokonan the Talker',
'Eyemi the Narcissist',
'Oni\',orses the Foolish',
'Treekness the Dark',
'Barbrosskam the Chief',
'Pikhoven the Deaf',
'Prikoko the Witless',
'Mushdrill the Piercer',
'Floratio the Investigator',
'Mushuliet the Catapulet',
'Edvushmunch the Screamer',
'Nidsally the Mushtang',
'Warazpacho the Cherrilla',
'Kojaklator the Lollipoper',
'Crackrodilrock the Helltune',
'Crabartanian the Allforone',
'Craborthos the All',
'Crabaramis the One',
'Crabathos the For',
'Crackedral the Majestic',
'Ezothbeitor the Neighbour',
'Arepotair the Bespectacled',
'Miomaho the Siciliano',
'Floramodovar the Stoned',
'Calipzoth the Icy',
'Ryukualak the Bored',
'Minoknok the Visitor',
'Zigzoth the Indecisive',
'Snailmetalika the Garagician',
'Kidodo the Extinct',
'Killua the Assassin',
'Misskokoko the Channel',
'Larvalaska the Cold',
'Ouassingiam the Tyrant',
'Moops the Bubbleboy',
'Don Quizothe the Stubborn',
'Supergwass the Free',
'Mufavabeenz the Cannibal',
'Palmella the Hefty',
'Palmpilot the Yuppie',
'Palmoleaf the Greasy',
'Naypalm the Herbivorous',
'Osurcus the Tamer',
'Zouzoth the Cuddly',
'Sparodi the Python',
'Ougathard the Fortunate',
'Mushketeer the Loyal',
'Trumpaynor the Survivor',
'Sacrier Dopple',
'Osamodas Dopple',
'Roy the Rover',
'Scaraheath the Hanger',
'Ougineemo the Lost',
'Sumens\',s Living Bag',
'Kwismas Whitish Fang',
'Major Arachnee',
'Bwork on the Run',
'Swimp the Simple',
'Dikal',
'Bone Idol',
'Nemik',
'Nekros',
'Pandawa Dopple',
'Attractive Barrel',
'Tree of Life',
'Summoned Treechnid',
'Lupus Minimus',
'Incarnam Scarecrow',
'Summoned Crackrock',
'Sauroshell',
'Manitou Zoth',
'Kwismas Minotoball',
'Da Rorc',
'Woolly Piggoth',
'Frighog',
'Kanigloo',
'Royal Pingwin',
'Pingwinkle',
'Mastogob',
'Mastogob Warrior',
'Venerable Mastogob',
'Mastogobbly',
'Royal Mastogob',
'Shaman Pingwin',
'Pingwobble',
'Mama Pingwin',
'Kung-Fu Pingwin',
'Cromagmunk',
'Sabredon',
'Apewicubic Bearbarian',
'Torpid Bearbarian',
'Vespal Bearbarian',
'Celestial Bearbarian',
'Steam Crackler',
'Atomystique',
'Mofette',
'Fumaroller',
'Solfatara',
'Talklyka Pirate',
'Karrybean Pirate',
'Vigi Pirate',
'Buck Anear',
'Harpy Pirate',
'Retspan Pirate',
'Yuara Pirate',
'Mega Plain Crackler',
'Bestial Brockhard',
'Venomous Brockhard',
'Gluttonous Brockhard',
'Nightcrawling Brockhard',
'Yokai Snowfoux',
'Maho Snowfoux',
'Soryo Snowfoux',
'Yomi Snowfoux',
'Stunted Rat',
'Crabeye',
'Dramanita',
'Fistulina',
'Fungore',
'Treecherous',
'Clump',
'Serpula',
'Mastoslob',
'Mister Penguin',
'Katigger',
'Pirate Bhey',
'The Masked Avenger',
'YeCh\',Ti',
'Dremoan',
'Flasho',
'Vinnie the Bearbarian',
'Woolly Bow Meow',
'Gullipop',
'Obsidemon',
'Buzta',
'Asploda',
'Grabba',
'Stabba',
'Bomma',
'Drilla',
'Gobshell',
'Grohlum',
'Ectobomb',
'Maglob',
'Hamrack',
'Kanniball Andchain',
'Haloperi Doll',
'Pyrotechnic Brockhard',
'Icy Brockhard',
'Tengu Snowfoux',
'Korriander',
'Sporachnee',
'Fuji Snowfoux',
'Dremoan Sprout',
'Boostache',
'Ashi-Magari',
'Kami Snowfoux',
'Kolosso',
'Esurient Bearbarian',
'Rampant Bearbarian',
'Mellifluous Bearbarian',
'Professor Xa',
'Kwakwa',
'Terrestrial Crobak',
'Lab Kolerat',
'Rabid Ouginak',
'Reinforced Scurvion',
'Nelween',
'Animated Gift',
'Stuffed Tofu',
'Stuffed Gobball',
'Stuffed Wabbit',
'Rogue Dopple',
'Kwismas Dragoturkey',
'Wild Kwismas Dragoturkey',
'Impetuous Kwismas Dragoturkey',
'Boombot',
'Rogue Dopple',
'Masqueraider Dopple',
'Small Animated Gift',
'Masqueraider Dopple',
'Gorgoyle',
'Grozilla',
'Grasmera',
'Raw Juvenile Sauroshell',
'Insipid Juvenile Sauroshell',
'Muddy Juvenile Sauroshell',
'Incandescent Juvenile Sauroshell',
'Moist Juvenile Sauroshell',
'Dry Juvenile Sauroshell',
'Insipid Novice Sauroshell',
'Muddy Novice Sauroshell',
'Incandescent Novice Sauroshell',
'Moist Novice Sauroshell',
'Dry Novice Sauroshell',
'Insipid Mature Sauroshell',
'Muddy Mature Sauroshell',
'Incandescent Mature Sauroshell',
'Moist Mature Sauroshell',
'Dry Mature Sauroshell',
'Insipid Venerable Sauroshell',
'Muddy Venerable Sauroshell',
'Incandescent Venerable Sauroshell',
'Moist Venerable Sauroshell',
'Dry Venerable Sauroshell',
'Raw Novice Sauroshell',
'Raw Mature Sauroshell',
'Raw Venerable Sauroshell',
'Sea Sauroshell',
'Moumouse Tourist',
'Sick Grossewer Shaman',
'Foster Fuji Snowfoux',
'Prepubescent Boostache',
'Ronin Chafer',
'Draugur Chafer',
'Primitive Chafer',
'Wind Bwak',
'Ice Bwak',
'Fire Bwak',
'Earth Bwak',
'Tired Grozilla',
'Exhausted Grozilla',
'Sleepwalking Grozilla',
'Tired Grasmera',
'Exhausted Grasmera',
'Sleepwalking Grasmera',
'Ugly Tofu',
'Blastofu',
'Tofubine',
'Podgy Tofu',
'Foggernaut Dopple',
'Pignolia',
'Al Howin',
'Devhorror',
'Arachkin',
'Toadkin',
'Worm-O\'-Lantern',
'Borbkin',
'Ghostly Young Wild Boar',
'Ghostly El Scarador',
'Ghostly Croum',
'Ghostly Crobak',
'Fire Kwakere Protector',
'Earth Kwakere Protector',
'Ice Kwakere Protector',
'Wind Kwakere Protector',
'Dopplesque Coney',
'Dopplesque Crackler',
'Dopplesque Boar',
'Dopplesque Gobball',
'Dopplesque Tofu',
'Dopplesque Bwork Magus',
'Dopplesque Red Wyrmling',
'Dopplesque Pandawasta',
'Dopplesque Madoll',
'Dopplesque Inflatable',
'Dopplesque Ultra-Powerful',
'Dopplesque Sacrificial Doll',
'Dopplesque Xelor\',s Dial',
'Creakrock',
'Ratworm',
'Ratfink',
'Packrat',
'Rugrat',
'Ratter',
'Brat',
'Riffrat',
'Prat',
'Lone Green Larva',
'Lone Blue Larva',
'Kwismas Bomberfu',
'Harrogant',
'Dumple',
'Putchup',
'Asteraw',
'Leatherball',
'Klime',
'Potbellion',
'Stalak',
'Karkanik',
'Skateman',
'Revish',
'Missiz Freezz',
'Nessil',
'Krackal',
'Dodox',
'Thermite',
'Snowdew',
'Nileza',
'Kan-O-Mat',
'Tinkerbear',
'Pingwinch',
'Mecanofoux',
'Serpulax',
'Sylargh',
'Bubotron',
'Treadfast',
'Cycloid',
'Sinistrofu',
'Nocturnowl',
'Count Harebourg',
'Mecanofoux Kidnapper',
'Serpulax Kidnapper',
'Poorly Messenger',
'Insatiable Blue Larva',
'Insatiable Green Larva',
'Insatiable Orange Larva',
'Revager',
'Inhabitant of Frigost',
'Labourer of the Count',
'Styffen Chillberg',
'Stray Stalak',
'Ghostly Krackal',
'Gaseous Creature',
'Malfunctioning Cycloid',
'Malfunctioning Bubotron',
'Malfunctioning Nocturnowl',
'Malfunctioning Sinistrofu',
'The Nutter',
'The Condemned',
'Wa Wobot',
'Black Wo Wabbit',
'Wobot Wosungwee',
'Whitepaw Wabbit',
'Skeleton Black Wabbit',
'Pwince Haiwy',
'Pwince Jowls',
'Pwince Willum',
'Aggressive Skeleton Wabbit',
'Tiwobot',
'Young Black Gobbly',
'Young White Gobbly',
'Small Gobball War Chief',
'Purple Lilpiwi',
'Small Tofu',
'Young Black Tofu',
'Paunchy Tofu',
'Young Tofoone',
'Young Boar',
'Young Sow',
'Luminescent Arachnee',
'Hairy Arachnee',
'Dark Gobball',
'Celestial Gobball',
'Grumpy Sandcastle',
'Big Sandcastle',
'Azure Plop',
'Crimson Plop',
'Dark Arachnee',
'Celestial Arachnee',
'Celestial Boar',
'Dark Tofu',
'Celestial Tofu',
'Dark Piwi',
'Tofinelle',
'Livid Boowolf',
'Aggressive Militiaman',
'Aggressive Warrior',
'Ghoulaurant',
'Ghoulverness',
'Ghroulm Serviss',
'Ghoulton',
'B\',one Shot',
'B\',one Doctor',
'B\',one Head',
'B\',one Boor',
'Staff Deleghoul',
'Troologram',
'Troololens',
'Trooligophren',
'Troolibrius',
'Crovus',
'Old Crobak',
'Cranky Crobak',
'Tyranike',
'Skirmisher Bwork',
'Folyo',
'Mastifang',
'Cyclouse',
'Stapleworm',
'Sharcut',
'Tremrus',
'Leatheraxer',
'Knockarock',
'Breakrock Knight',
'Yobbomark Knight',
'Yobreaker',
'Major-Yoberal Selim Quartz',
'Flo Inghair',
'Peb\',Houlud',
'White Mastifang',
'Dokachu',
'Dolbinos',
'Dolivar',
'Domoizelle',
'Dostrogo',
'Croclingy',
'Ul\',Khan',
'Al Howin',
'B\',one Shot',
'Boostache',
'Mucane',
'Shushkebab',
'Shushuaia',
'Shuchu',
'Shushlicker',
'Shushlicker',
'Shushlicker',
'Crocodyl Attacker',
'Belligerent Young Crocodyl',
'Crocodyl Attacker',
'Crocodyl Attacker',
'Crocodyl Attacker',
'Crocopike',
'Anchodyl',
'Feathodyl',
'Crocelmet',
'Scale King',
'Mastigator',
'Crokveeno',
'Disorientated Shusurper',
'Inept Shusurper',
'Distraught Shusurper',
'Manderisha',
'Dodegg',
'Mushonk',
'Boar',
'Gobball',
'Red Wyrmling',
'Astrub Squirrel',
'Rokoko',
'Beaztinga',
'Bliblimead',
'Bliblycerin',
'Blibliternal',
'Bliblitch',
'Weirbwork',
'Burnabwork',
'Mabwork',
'Megabwork',
'Sucgunner',
'Funerbroadsword',
'Micrab',
'Drowhirl',
'Zombrute',
'Kanigrula',
'Orfan',
'Kannihilator',
'Felygiene',
'Alyeena',
'Cracklerge',
'Elemearth',
'Cracklope',
'Crakillian Guardian',
'Crackblade',
'Miliboowolf',
'Mature Kaniger',
'Summoned Plissken',
'Captive Cracklope',
'Bontarian Detachment',
'Bworkokorral',
'Plains Larva',
'Garglyph',
'Miliboowolf Scout',
'Fangshu',
'Hanshi',
'Ino-Naru',
'Kurookin',
'Lichangoro',
'Shihan',
'Uchiwang',
'Akakwa',
'Baka',
'Kwakumber',
'Kwamurai',
'Nagate',
'Blokapwane',
'Boombardier',
'Spitfoux',
'Fouxnamballist',
'Founoroshi',
'Bangartifoux',
'Gingerocket',
'Ishibig Pak',
'Tatatojiki',
'Parashutackle',
'Shinobuubusu',
'Tanukouï San',
'Titinuki',
'Aggressive Akakwa'];
